version: "3"
services:

  master:
    image: tovsyannikov/master
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - shared_net

  worker:
    image: tovsyannikov/worker
    networks:
      - shared_net
    deploy:
      replicas: 2

  redis_db:
    image: redis
    networks:
      - shared_net

networks:
  shared_net: